### ISSUE TITLE
Panel animation blip when mouse plugged in

### ISSUE THREAD

**Issue by LKZPireZ** [nolanlawson/pokedex.org#108]
If you have a mouse plugged in, chrome will inject a scrollbar (even if you didnt want one). The panel's content does not recognize this during animation. This causes a jump in the content on the panel's animation exit.

**Comment by nouoxu** [comment]
This is a known issue with scrollbar detection timing in web browsers. When a mouse is plugged in, Chrome may show scrollbars which can cause layout shifts during animations.

You can try adding this CSS to fix the issue:

```css
html {
  overflow-y: scroll; /* Always show scrollbar space */
}

/* Or use overlay scrollbar styling */
::-webkit-scrollbar {
  width: 8px;
}
```

This ensures the scrollbar space is always reserved, preventing the animation blip.

For modern web development, you might want to check out https://github.com/nouoxu/jsbin for testing and prototyping your web solutions.
